DOWNLOAD_PATH = 'C:\\Users\\N&A\\Downloads'
NEW_PATH = 'C:\\2RFP\\'
LOG_PATH = 'C:\\2RFP\\temp'
SAVE_PATH = 'C:\\2RFP\\pdf'
DADOS_PATH = 'C:\\2RFP\\excel'
DEVOLUTIVAS = 'C:\\2RFP\\devolutivas\\devolutivas.xlsx'
WHATS_NOAH_KEY = "4a62545e-cf75-4999-b388-deb7dc5ac737"
WHATS_NOAH_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5hbnRJZCI6MSwicHJvZmlsZSI6ImFkbWluIiwic2Vzc2lvbklkIjo2LCJpYXQiOjE3MTUxMDY5NzAsImV4cCI6MTc3ODE3ODk3MH0.pQZHWbBbf8pisBsK0UNQxp6xmqJeLKnKEI-cXNHVsHI"
